// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: port.sql

package db

import (
	"context"
)

const countPorts = `-- name: CountPorts :one
SELECT COUNT(*) FROM port
`

func (q *Queries) CountPorts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPorts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPort = `-- name: CreatePort :one
INSERT INTO port (ip_id, port) VALUES ($1, $2) RETURNING id, ip_id, port, created_at, updated_at
`

type CreatePortParams struct {
	IpID int64 `json:"ip_id"`
	Port int32 `json:"port"`
}

func (q *Queries) CreatePort(ctx context.Context, arg CreatePortParams) (Port, error) {
	row := q.db.QueryRow(ctx, createPort, arg.IpID, arg.Port)
	var i Port
	err := row.Scan(
		&i.ID,
		&i.IpID,
		&i.Port,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePortByIDs = `-- name: DeletePortByIDs :exec
DELETE FROM port WHERE id = $1
`

func (q *Queries) DeletePortByIDs(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePortByIDs, id)
	return err
}

const findPortByIDs = `-- name: FindPortByIDs :one
SELECT id, ip_id, port, created_at, updated_at FROM port WHERE id = $1 LIMIT 1
`

func (q *Queries) FindPortByIDs(ctx context.Context, id int64) (Port, error) {
	row := q.db.QueryRow(ctx, findPortByIDs, id)
	var i Port
	err := row.Scan(
		&i.ID,
		&i.IpID,
		&i.Port,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPorts = `-- name: FindPorts :many
SELECT id, ip_id, port, created_at, updated_at FROM port LIMIT $1 OFFSET $2
`

type FindPortsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) FindPorts(ctx context.Context, arg FindPortsParams) ([]Port, error) {
	rows, err := q.db.Query(ctx, findPorts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Port{}
	for rows.Next() {
		var i Port
		if err := rows.Scan(
			&i.ID,
			&i.IpID,
			&i.Port,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPortsWithIpID = `-- name: FindPortsWithIpID :many
SELECT id, ip_id, port, created_at, updated_at FROM port WHERE ip_id = $1 LIMIT $2 OFFSET $3
`

type FindPortsWithIpIDParams struct {
	IpID   int64 `json:"ip_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) FindPortsWithIpID(ctx context.Context, arg FindPortsWithIpIDParams) ([]Port, error) {
	rows, err := q.db.Query(ctx, findPortsWithIpID, arg.IpID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Port{}
	for rows.Next() {
		var i Port
		if err := rows.Scan(
			&i.ID,
			&i.IpID,
			&i.Port,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPortsWithPort = `-- name: FindPortsWithPort :many
SELECT id, ip_id, port, created_at, updated_at FROM port WHERE port = $1  LIMIT $2 OFFSET $3
`

type FindPortsWithPortParams struct {
	Port   int32 `json:"port"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) FindPortsWithPort(ctx context.Context, arg FindPortsWithPortParams) ([]Port, error) {
	rows, err := q.db.Query(ctx, findPortsWithPort, arg.Port, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Port{}
	for rows.Next() {
		var i Port
		if err := rows.Scan(
			&i.ID,
			&i.IpID,
			&i.Port,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePort = `-- name: UpdatePort :one
UPDATE port SET ip_id = $2, port = $3, updated_at = NOW() WHERE id = $1 RETURNING id, ip_id, port, created_at, updated_at
`

type UpdatePortParams struct {
	ID   int64 `json:"id"`
	IpID int64 `json:"ip_id"`
	Port int32 `json:"port"`
}

func (q *Queries) UpdatePort(ctx context.Context, arg UpdatePortParams) (Port, error) {
	row := q.db.QueryRow(ctx, updatePort, arg.ID, arg.IpID, arg.Port)
	var i Port
	err := row.Scan(
		&i.ID,
		&i.IpID,
		&i.Port,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
