// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreateApi(ctx context.Context, arg CreateApiParams) (Api, error)
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	CreatePlatform(ctx context.Context, arg CreatePlatformParams) (Platform, error)
	CreateProgram(ctx context.Context, arg CreateProgramParams) (Program, error)
	CreateReset(ctx context.Context, arg CreateResetParams) (Reset, error)
	CreateScope(ctx context.Context, arg CreateScopeParams) (Scope, error)
	CreateStat(ctx context.Context, arg CreateStatParams) (Stat, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteApiByIDs(ctx context.Context, id int64) error
	DeleteNote(ctx context.Context, id int64) error
	DeletePlatformByIDs(ctx context.Context, id int64) error
	DeleteProgramByIDs(ctx context.Context, id int64) error
	DeleteProgramBySlug(ctx context.Context, slug string) error
	DeleteResetsForUser(ctx context.Context, userID int64) error
	DeleteScopeByID(ctx context.Context, id int64) error
	DeleteStatByID(ctx context.Context, id int64) error
	FindApiByIDs(ctx context.Context, id int64) (Api, error)
	FindApis(ctx context.Context) ([]Api, error)
	FindNoteByID(ctx context.Context, id int64) (Note, error)
	FindNotes(ctx context.Context) ([]Note, error)
	FindNotesByProgramID(ctx context.Context, programID int64) ([]Note, error)
	FindPlatformByIDs(ctx context.Context, id int64) (FindPlatformByIDsRow, error)
	FindPlatforms(ctx context.Context) ([]FindPlatformsRow, error)
	FindProgramByIDs(ctx context.Context, id int64) (Program, error)
	FindProgramBySlug(ctx context.Context, slug string) (Program, error)
	FindPrograms(ctx context.Context) ([]Program, error)
	FindResetByCode(ctx context.Context, code string) (Reset, error)
	FindScopeByID(ctx context.Context, id int64) (Scope, error)
	FindScopes(ctx context.Context) ([]Scope, error)
	FindScopesByProgramID(ctx context.Context, programID int64) ([]Scope, error)
	FindStatByID(ctx context.Context, id int64) (Stat, error)
	FindStatByReportID(ctx context.Context, reportID string) (Stat, error)
	FindStats(ctx context.Context) ([]Stat, error)
	FindUserByEmail(ctx context.Context, lower string) (User, error)
	FindUserByID(ctx context.Context, id int64) (User, error)
	FindUserByVerificationCode(ctx context.Context, verification string) (User, error)
	GetPlatforms(ctx context.Context) ([]Platform, error)
	GetScopeByProgramIDAndScope(ctx context.Context, arg GetScopeByProgramIDAndScopeParams) (Scope, error)
	UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error)
	UpdatePlatform(ctx context.Context, arg UpdatePlatformParams) (Platform, error)
	UpdateProgram(ctx context.Context, arg UpdateProgramParams) (Program, error)
	UpdateStat(ctx context.Context, arg UpdateStatParams) (Stat, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
}

var _ Querier = (*Queries)(nil)
