// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: subdomain.sql

package db

import (
	"context"
)

const countSubdomains = `-- name: CountSubdomains :one
SELECT COUNT(*) FROM subdomain
`

func (q *Queries) CountSubdomains(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSubdomains)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubdomainsWithProgramID = `-- name: CountSubdomainsWithProgramID :one
SELECT COUNT(*) FROM subdomain WHERE program_id = $1
`

func (q *Queries) CountSubdomainsWithProgramID(ctx context.Context, programID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countSubdomainsWithProgramID, programID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubdomainsWithProgramIDAndTechnologies = `-- name: CountSubdomainsWithProgramIDAndTechnologies :one
SELECT COUNT(*) FROM subdomain WHERE program_id = $1 AND string_to_array(technologies, ',') && string_to_array($2, ',')
`

type CountSubdomainsWithProgramIDAndTechnologiesParams struct {
	ProgramID     int64  `json:"program_id"`
	StringToArray string `json:"string_to_array"`
}

func (q *Queries) CountSubdomainsWithProgramIDAndTechnologies(ctx context.Context, arg CountSubdomainsWithProgramIDAndTechnologiesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSubdomainsWithProgramIDAndTechnologies, arg.ProgramID, arg.StringToArray)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubdomainsWithSearch = `-- name: CountSubdomainsWithSearch :one
SELECT COUNT(*) FROM subdomain WHERE subdomain LIKE $1
`

func (q *Queries) CountSubdomainsWithSearch(ctx context.Context, subdomain string) (int64, error) {
	row := q.db.QueryRow(ctx, countSubdomainsWithSearch, subdomain)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubdomainsWithSearchAndProgramID = `-- name: CountSubdomainsWithSearchAndProgramID :one
SELECT COUNT(*) FROM subdomain WHERE subdomain LIKE $1 AND program_id = $2
`

type CountSubdomainsWithSearchAndProgramIDParams struct {
	Subdomain string `json:"subdomain"`
	ProgramID int64  `json:"program_id"`
}

func (q *Queries) CountSubdomainsWithSearchAndProgramID(ctx context.Context, arg CountSubdomainsWithSearchAndProgramIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSubdomainsWithSearchAndProgramID, arg.Subdomain, arg.ProgramID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubdomainsWithSearchAndProgramIDAndTechnologies = `-- name: CountSubdomainsWithSearchAndProgramIDAndTechnologies :one
SELECT COUNT(*) FROM subdomain WHERE subdomain LIKE $1 AND program_id = $2 AND string_to_array(technologies, ',') && string_to_array($3, ',')
`

type CountSubdomainsWithSearchAndProgramIDAndTechnologiesParams struct {
	Subdomain     string `json:"subdomain"`
	ProgramID     int64  `json:"program_id"`
	StringToArray string `json:"string_to_array"`
}

func (q *Queries) CountSubdomainsWithSearchAndProgramIDAndTechnologies(ctx context.Context, arg CountSubdomainsWithSearchAndProgramIDAndTechnologiesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSubdomainsWithSearchAndProgramIDAndTechnologies, arg.Subdomain, arg.ProgramID, arg.StringToArray)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubdomainsWithSearchAndTechnologies = `-- name: CountSubdomainsWithSearchAndTechnologies :one
SELECT COUNT(*) FROM subdomain WHERE subdomain LIKE $1 AND string_to_array(technologies, ',') && string_to_array($2, ',')
`

type CountSubdomainsWithSearchAndTechnologiesParams struct {
	Subdomain     string `json:"subdomain"`
	StringToArray string `json:"string_to_array"`
}

func (q *Queries) CountSubdomainsWithSearchAndTechnologies(ctx context.Context, arg CountSubdomainsWithSearchAndTechnologiesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSubdomainsWithSearchAndTechnologies, arg.Subdomain, arg.StringToArray)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubdomainsWithTechnologies = `-- name: CountSubdomainsWithTechnologies :one
SELECT COUNT(*) FROM subdomain WHERE string_to_array(technologies, ',') && string_to_array($1, ',')
`

func (q *Queries) CountSubdomainsWithTechnologies(ctx context.Context, stringToArray string) (int64, error) {
	row := q.db.QueryRow(ctx, countSubdomainsWithTechnologies, stringToArray)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubdomain = `-- name: CreateSubdomain :one
INSERT INTO subdomain (program_id, subdomain, title, body_hash, status_code, technologies, content_length, tag, port) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, program_id, subdomain, tag, port, title, body_hash, status_code, technologies, content_length, favourite, created_at, updated_at
`

type CreateSubdomainParams struct {
	ProgramID     int64  `json:"program_id"`
	Subdomain     string `json:"subdomain"`
	Title         string `json:"title"`
	BodyHash      string `json:"body_hash"`
	StatusCode    int32  `json:"status_code"`
	Technologies  string `json:"technologies"`
	ContentLength int32  `json:"content_length"`
	Tag           string `json:"tag"`
	Port          string `json:"port"`
}

func (q *Queries) CreateSubdomain(ctx context.Context, arg CreateSubdomainParams) (Subdomain, error) {
	row := q.db.QueryRow(ctx, createSubdomain,
		arg.ProgramID,
		arg.Subdomain,
		arg.Title,
		arg.BodyHash,
		arg.StatusCode,
		arg.Technologies,
		arg.ContentLength,
		arg.Tag,
		arg.Port,
	)
	var i Subdomain
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.Subdomain,
		&i.Tag,
		&i.Port,
		&i.Title,
		&i.BodyHash,
		&i.StatusCode,
		&i.Technologies,
		&i.ContentLength,
		&i.Favourite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubdomainByIDs = `-- name: DeleteSubdomainByIDs :exec
DELETE FROM subdomain WHERE id = $1
`

func (q *Queries) DeleteSubdomainByIDs(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSubdomainByIDs, id)
	return err
}

const favouriteSubdomain = `-- name: FavouriteSubdomain :one
UPDATE subdomain SET favourite = $2, updated_at = NOW() WHERE id = $1 RETURNING id, program_id, subdomain, tag, port, title, body_hash, status_code, technologies, content_length, favourite, created_at, updated_at
`

type FavouriteSubdomainParams struct {
	ID        int64 `json:"id"`
	Favourite bool  `json:"favourite"`
}

func (q *Queries) FavouriteSubdomain(ctx context.Context, arg FavouriteSubdomainParams) (Subdomain, error) {
	row := q.db.QueryRow(ctx, favouriteSubdomain, arg.ID, arg.Favourite)
	var i Subdomain
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.Subdomain,
		&i.Tag,
		&i.Port,
		&i.Title,
		&i.BodyHash,
		&i.StatusCode,
		&i.Technologies,
		&i.ContentLength,
		&i.Favourite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findSubdomainByIDs = `-- name: FindSubdomainByIDs :one
SELECT id, program_id, subdomain, tag, port, title, body_hash, status_code, technologies, content_length, favourite, created_at, updated_at FROM subdomain WHERE id = $1 LIMIT 1
`

func (q *Queries) FindSubdomainByIDs(ctx context.Context, id int64) (Subdomain, error) {
	row := q.db.QueryRow(ctx, findSubdomainByIDs, id)
	var i Subdomain
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.Subdomain,
		&i.Tag,
		&i.Port,
		&i.Title,
		&i.BodyHash,
		&i.StatusCode,
		&i.Technologies,
		&i.ContentLength,
		&i.Favourite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findSubdomainByProgram = `-- name: FindSubdomainByProgram :many
SELECT id, program_id, subdomain, tag, port, title, body_hash, status_code, technologies, content_length, favourite, created_at, updated_at FROM subdomain WHERE program_id = $1
`

func (q *Queries) FindSubdomainByProgram(ctx context.Context, programID int64) ([]Subdomain, error) {
	rows, err := q.db.Query(ctx, findSubdomainByProgram, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subdomain{}
	for rows.Next() {
		var i Subdomain
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.Subdomain,
			&i.Tag,
			&i.Port,
			&i.Title,
			&i.BodyHash,
			&i.StatusCode,
			&i.Technologies,
			&i.ContentLength,
			&i.Favourite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSubdomains = `-- name: FindSubdomains :many
SELECT id, program_id, subdomain, tag, port, title, body_hash, status_code, technologies, content_length, favourite, created_at, updated_at FROM subdomain LIMIT $1 OFFSET $2
`

type FindSubdomainsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) FindSubdomains(ctx context.Context, arg FindSubdomainsParams) ([]Subdomain, error) {
	rows, err := q.db.Query(ctx, findSubdomains, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subdomain{}
	for rows.Next() {
		var i Subdomain
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.Subdomain,
			&i.Tag,
			&i.Port,
			&i.Title,
			&i.BodyHash,
			&i.StatusCode,
			&i.Technologies,
			&i.ContentLength,
			&i.Favourite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSubdomainsWithProgramID = `-- name: FindSubdomainsWithProgramID :many
SELECT id, program_id, subdomain, tag, port, title, body_hash, status_code, technologies, content_length, favourite, created_at, updated_at FROM subdomain WHERE program_id = $1 LIMIT $2 OFFSET $3
`

type FindSubdomainsWithProgramIDParams struct {
	ProgramID int64 `json:"program_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) FindSubdomainsWithProgramID(ctx context.Context, arg FindSubdomainsWithProgramIDParams) ([]Subdomain, error) {
	rows, err := q.db.Query(ctx, findSubdomainsWithProgramID, arg.ProgramID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subdomain{}
	for rows.Next() {
		var i Subdomain
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.Subdomain,
			&i.Tag,
			&i.Port,
			&i.Title,
			&i.BodyHash,
			&i.StatusCode,
			&i.Technologies,
			&i.ContentLength,
			&i.Favourite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSubdomainsWithProgramIDAndTechnologies = `-- name: FindSubdomainsWithProgramIDAndTechnologies :many
SELECT id, program_id, subdomain, tag, port, title, body_hash, status_code, technologies, content_length, favourite, created_at, updated_at FROM subdomain WHERE program_id = $1 AND string_to_array(technologies, ',') && string_to_array($2, ',') LIMIT $3 OFFSET $4
`

type FindSubdomainsWithProgramIDAndTechnologiesParams struct {
	ProgramID     int64  `json:"program_id"`
	StringToArray string `json:"string_to_array"`
	Limit         int32  `json:"limit"`
	Offset        int32  `json:"offset"`
}

func (q *Queries) FindSubdomainsWithProgramIDAndTechnologies(ctx context.Context, arg FindSubdomainsWithProgramIDAndTechnologiesParams) ([]Subdomain, error) {
	rows, err := q.db.Query(ctx, findSubdomainsWithProgramIDAndTechnologies,
		arg.ProgramID,
		arg.StringToArray,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subdomain{}
	for rows.Next() {
		var i Subdomain
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.Subdomain,
			&i.Tag,
			&i.Port,
			&i.Title,
			&i.BodyHash,
			&i.StatusCode,
			&i.Technologies,
			&i.ContentLength,
			&i.Favourite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSubdomainsWithSearch = `-- name: FindSubdomainsWithSearch :many
SELECT id, program_id, subdomain, tag, port, title, body_hash, status_code, technologies, content_length, favourite, created_at, updated_at FROM subdomain WHERE subdomain LIKE $1 LIMIT $2 OFFSET $3
`

type FindSubdomainsWithSearchParams struct {
	Subdomain string `json:"subdomain"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) FindSubdomainsWithSearch(ctx context.Context, arg FindSubdomainsWithSearchParams) ([]Subdomain, error) {
	rows, err := q.db.Query(ctx, findSubdomainsWithSearch, arg.Subdomain, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subdomain{}
	for rows.Next() {
		var i Subdomain
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.Subdomain,
			&i.Tag,
			&i.Port,
			&i.Title,
			&i.BodyHash,
			&i.StatusCode,
			&i.Technologies,
			&i.ContentLength,
			&i.Favourite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSubdomainsWithSearchAndProgramID = `-- name: FindSubdomainsWithSearchAndProgramID :many
SELECT id, program_id, subdomain, tag, port, title, body_hash, status_code, technologies, content_length, favourite, created_at, updated_at FROM subdomain WHERE subdomain LIKE $1 AND program_id = $2 LIMIT $3 OFFSET $4
`

type FindSubdomainsWithSearchAndProgramIDParams struct {
	Subdomain string `json:"subdomain"`
	ProgramID int64  `json:"program_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) FindSubdomainsWithSearchAndProgramID(ctx context.Context, arg FindSubdomainsWithSearchAndProgramIDParams) ([]Subdomain, error) {
	rows, err := q.db.Query(ctx, findSubdomainsWithSearchAndProgramID,
		arg.Subdomain,
		arg.ProgramID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subdomain{}
	for rows.Next() {
		var i Subdomain
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.Subdomain,
			&i.Tag,
			&i.Port,
			&i.Title,
			&i.BodyHash,
			&i.StatusCode,
			&i.Technologies,
			&i.ContentLength,
			&i.Favourite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSubdomainsWithSearchAndProgramIDAndTechnologies = `-- name: FindSubdomainsWithSearchAndProgramIDAndTechnologies :many
SELECT id, program_id, subdomain, tag, port, title, body_hash, status_code, technologies, content_length, favourite, created_at, updated_at FROM subdomain WHERE subdomain LIKE $1 AND program_id = $2 AND string_to_array(technologies, ',') && string_to_array($3, ',') LIMIT $4 OFFSET $5
`

type FindSubdomainsWithSearchAndProgramIDAndTechnologiesParams struct {
	Subdomain     string `json:"subdomain"`
	ProgramID     int64  `json:"program_id"`
	StringToArray string `json:"string_to_array"`
	Limit         int32  `json:"limit"`
	Offset        int32  `json:"offset"`
}

func (q *Queries) FindSubdomainsWithSearchAndProgramIDAndTechnologies(ctx context.Context, arg FindSubdomainsWithSearchAndProgramIDAndTechnologiesParams) ([]Subdomain, error) {
	rows, err := q.db.Query(ctx, findSubdomainsWithSearchAndProgramIDAndTechnologies,
		arg.Subdomain,
		arg.ProgramID,
		arg.StringToArray,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subdomain{}
	for rows.Next() {
		var i Subdomain
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.Subdomain,
			&i.Tag,
			&i.Port,
			&i.Title,
			&i.BodyHash,
			&i.StatusCode,
			&i.Technologies,
			&i.ContentLength,
			&i.Favourite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSubdomainsWithSearchAndTechnologies = `-- name: FindSubdomainsWithSearchAndTechnologies :many
SELECT id, program_id, subdomain, tag, port, title, body_hash, status_code, technologies, content_length, favourite, created_at, updated_at FROM subdomain WHERE subdomain LIKE $1 AND string_to_array(technologies, ',') && string_to_array($2, ',') LIMIT $3 OFFSET $4
`

type FindSubdomainsWithSearchAndTechnologiesParams struct {
	Subdomain     string `json:"subdomain"`
	StringToArray string `json:"string_to_array"`
	Limit         int32  `json:"limit"`
	Offset        int32  `json:"offset"`
}

func (q *Queries) FindSubdomainsWithSearchAndTechnologies(ctx context.Context, arg FindSubdomainsWithSearchAndTechnologiesParams) ([]Subdomain, error) {
	rows, err := q.db.Query(ctx, findSubdomainsWithSearchAndTechnologies,
		arg.Subdomain,
		arg.StringToArray,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subdomain{}
	for rows.Next() {
		var i Subdomain
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.Subdomain,
			&i.Tag,
			&i.Port,
			&i.Title,
			&i.BodyHash,
			&i.StatusCode,
			&i.Technologies,
			&i.ContentLength,
			&i.Favourite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSubdomainsWithTechnologies = `-- name: FindSubdomainsWithTechnologies :many
SELECT id, program_id, subdomain, tag, port, title, body_hash, status_code, technologies, content_length, favourite, created_at, updated_at FROM subdomain WHERE string_to_array(technologies, ',') && string_to_array($1, ',') LIMIT $2 OFFSET $3
`

type FindSubdomainsWithTechnologiesParams struct {
	StringToArray string `json:"string_to_array"`
	Limit         int32  `json:"limit"`
	Offset        int32  `json:"offset"`
}

func (q *Queries) FindSubdomainsWithTechnologies(ctx context.Context, arg FindSubdomainsWithTechnologiesParams) ([]Subdomain, error) {
	rows, err := q.db.Query(ctx, findSubdomainsWithTechnologies, arg.StringToArray, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subdomain{}
	for rows.Next() {
		var i Subdomain
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.Subdomain,
			&i.Tag,
			&i.Port,
			&i.Title,
			&i.BodyHash,
			&i.StatusCode,
			&i.Technologies,
			&i.ContentLength,
			&i.Favourite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTechnologiesForAllSubdomains = `-- name: GetTechnologiesForAllSubdomains :many
SELECT technologies FROM subdomain
`

func (q *Queries) GetTechnologiesForAllSubdomains(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getTechnologiesForAllSubdomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var technologies string
		if err := rows.Scan(&technologies); err != nil {
			return nil, err
		}
		items = append(items, technologies)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubdomain = `-- name: UpdateSubdomain :one
UPDATE subdomain SET program_id = $2, subdomain = $3, title = $4, body_hash = $5, status_code = $6, technologies = $7, content_length = $8, tag = $9, port = $10, updated_at = NOW() WHERE id = $1 RETURNING id, program_id, subdomain, tag, port, title, body_hash, status_code, technologies, content_length, favourite, created_at, updated_at
`

type UpdateSubdomainParams struct {
	ID            int64  `json:"id"`
	ProgramID     int64  `json:"program_id"`
	Subdomain     string `json:"subdomain"`
	Title         string `json:"title"`
	BodyHash      string `json:"body_hash"`
	StatusCode    int32  `json:"status_code"`
	Technologies  string `json:"technologies"`
	ContentLength int32  `json:"content_length"`
	Tag           string `json:"tag"`
	Port          string `json:"port"`
}

func (q *Queries) UpdateSubdomain(ctx context.Context, arg UpdateSubdomainParams) (Subdomain, error) {
	row := q.db.QueryRow(ctx, updateSubdomain,
		arg.ID,
		arg.ProgramID,
		arg.Subdomain,
		arg.Title,
		arg.BodyHash,
		arg.StatusCode,
		arg.Technologies,
		arg.ContentLength,
		arg.Tag,
		arg.Port,
	)
	var i Subdomain
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.Subdomain,
		&i.Tag,
		&i.Port,
		&i.Title,
		&i.BodyHash,
		&i.StatusCode,
		&i.Technologies,
		&i.ContentLength,
		&i.Favourite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
