export const GET_PLATFORM = 'GET_PLATFORM';
export const GET_PLATFORM_ERROR = 'GET_PLATFORM_ERROR';

export const CREATE_PLATFORM = 'CREATE_PLATFORM';
export const CREATE_PLATFORM_ERROR = 'CREATE_PLATFORM_ERROR';

export const UPDATE_PLATFORM = 'UPDATE_PLATFORM';
export const UPDATE_PLATFORM_ERROR = 'UPDATE_PLATFORM_ERROR';

export const DELETE_PLATFORM = 'DELETE_PLATFORM';
export const DELETE_PLATFORM_ERROR = 'DELETE_PLATFORM_ERROR';