export const GET_PROGRAM = 'GET_PROGRAM';
export const GET_PROGRAM_SUCCESS = 'GET_PROGRAM_SUCCESS';
export const GET_PROGRAM_ERROR = 'GET_PROGRAM_ERROR';

export const CREATE_PROGRAM = 'CREATE_PROGRAM';
export const CREATE_PROGRAM_SUCCESS = 'CREATE_PROGRAM_SUCCESS';
export const CREATE_PROGRAM_ERROR = 'CREATE_PROGRAM_ERROR';

export const RELOAD_PROGRAM = 'RELOAD_PROGRAM';
export const RELOAD_PROGRAM_SUCCESS = 'RELOAD_PROGRAM_SUCCESS';
export const RELOAD_PROGRAM_ERROR = 'RELOAD_PROGRAM_ERROR';

export const UPDATE_PROGRAM = 'UPDATE_PROGRAM';
export const UPDATE_PROGRAM_SUCCESS = 'UPDATE_PROGRAM_SUCCESS';
export const UPDATE_PROGRAM_ERROR = 'UPDATE_PROGRAM_ERROR';

export const DELETE_PROGRAM = 'DELETE_PROGRAM';
export const DELETE_PROGRAM_SUCCESS = 'DELETE_PROGRAM_SUCCESS';
export const DELETE_PROGRAM_ERROR = 'DELETE_PROGRAM_ERROR';

export const GET_SCOPE = 'GET_SCOPE';
export const GET_SCOPE_SUCCESS = 'GET_SCOPE_SUCCESS';
export const GET_SCOPE_ERROR = 'GET_SCOPE_ERROR';