export const GET_PROGRAM = 'GET_PROGRAM';
export const GET_PROGRAM_ERROR = 'GET_PROGRAM_ERROR';

export const CREATE_PROGRAM = 'CREATE_PROGRAM';
export const CREATE_PROGRAM_ERROR = 'CREATE_PROGRAM_ERROR';

export const UPDATE_PROGRAM = 'UPDATE_PROGRAM';
export const UPDATE_PROGRAM_ERROR = 'UPDATE_PROGRAM_ERROR';

export const DELETE_PROGRAM = 'DELETE_PROGRAM';
export const DELETE_PROGRAM_ERROR = 'DELETE_PROGRAM_ERROR';