export const GET_REVENUE = 'GET_REVENUE';
export const GET_REVENUE_ERROR = 'GET_REVENUE_ERROR';

export const CREATE_REVENUE = 'CREATE_REVENUE';
export const CREATE_REVENUE_ERROR = 'CREATE_REVENUE_ERROR';

export const UPDATE_REVENUE = 'UPDATE_REVENUE';
export const UPDATE_REVENUE_ERROR = 'UPDATE_REVENUE_ERROR';

export const DELETE_REVENUE = 'DELETE_REVENUE';
export const DELETE_REVENUE_ERROR = 'DELETE_REVENUE_ERROR';