export const GET_SCANS = 'GET_SCANS';
export const GET_SCANS_SUCCESS = 'GET_SCANS_SUCCESS';
export const GET_SCANS_ERROR = 'GET_SCANS_ERROR';

export const CREATE_SCAN = 'CREATE_SCAN';
export const CREATE_SCAN_SUCCESS = 'CREATE_SCAN_SUCCESS';
export const CREATE_SCAN_ERROR = 'CREATE_SCAN_ERROR';

export const DELETE_SCAN = 'DELETE_SCAN';
export const DELETE_SCAN_SUCCESS = 'DELETE_SCAN_SUCCESS';
export const DELETE_SCAN_ERROR = 'DELETE_SCAN_ERROR';