export const GET_API_KEY = 'GET_API_KEY';
export const GET_API_KEY_ERROR = 'GET_API_KEY_ERROR';

export const CREATE_API_KEY = 'CREATE_API_KEY';
export const CREATE_API_KEY_ERROR = 'CREATE_API_KEY_ERROR';

export const DELETE_API_KEY = 'DELETE_API_KEY';
export const DELETE_API_KEY_ERROR = 'DELETE_API_KEY_ERROR';

export const PULL_RUBYX_DATA = 'PULL_RUBYX_DATA';
export const PULL_RUBYX_DATA_ERROR = 'PULL_RUBYX_DATA_ERROR';
export const PULL_RUBYX_DATA_SUCCESS = 'PULL_RUBYX_DATA_SUCCESS';

export const GET_DATA_REPO_URL = 'GET_DATA_REPO_URL';
export const GET_DATA_REPO_URL_ERROR = 'GET_DATA_REPO_URL_ERROR';
export const GET_DATA_REPO_URL_SUCCESS = 'GET_DATA_REPO_URL_SUCCESS';

export const SET_DATA_REPO_URL = 'SET_DATA_REPO_URL';
export const SET_DATA_REPO_URL_ERROR = 'SET_DATA_REPO_URL_ERROR';
export const SET_DATA_REPO_URL_SUCCESS = 'SET_DATA_REPO_URL_SUCCESS';