export const GET_SUBDOMAIN = 'GET_SUBDOMAIN';
export const GET_SUBDOMAIN_SUCCESS = 'GET_SUBDOMAIN_SUCCESS';
export const GET_SUBDOMAIN_ERROR = 'GET_SUBDOMAIN_ERROR';

export const GET_UNIQUE_TECHNOLOGIES = 'GET_UNIQUE_TECHNOLOGIES';
export const GET_UNIQUE_TECHNOLOGIES_SUCCESS = 'GET_UNIQUE_TECHNOLOGIES_SUCCESS';
export const GET_UNIQUE_TECHNOLOGIES_ERROR = 'GET_UNIQUE_TECHNOLOGIES_ERROR';