export const GET_SUBDOMAIN = 'GET_SUBDOMAIN';
export const GET_SUBDOMAIN_SUCCESS = 'GET_SUBDOMAIN_SUCCESS';
export const GET_SUBDOMAIN_ERROR = 'GET_SUBDOMAIN_ERROR';

export const GET_UNIQUE_TECHNOLOGIES = 'GET_UNIQUE_TECHNOLOGIES';
export const GET_UNIQUE_TECHNOLOGIES_SUCCESS = 'GET_UNIQUE_TECHNOLOGIES_SUCCESS';
export const GET_UNIQUE_TECHNOLOGIES_ERROR = 'GET_UNIQUE_TECHNOLOGIES_ERROR';

export const CREATE_SUBDOMAIN = 'CREATE_SUBDOMAIN';
export const CREATE_SUBDOMAIN_ERROR = 'CREATE_SUBDOMAIN_ERROR';

export const UPDATE_SUBDOMAIN = 'UPDATE_SUBDOMAIN';
export const UPDATE_SUBDOMAIN_ERROR = 'UPDATE_SUBDOMAIN_ERROR';

export const DELETE_SUBDOMAIN = 'DELETE_SUBDOMAIN';
export const DELETE_SUBDOMAIN_ERROR = 'DELETE_SUBDOMAIN_ERROR';