export const GET_SUBDOMAIN = 'GET_SUBDOMAIN';
export const GET_SUBDOMAIN_ERROR = 'GET_SUBDOMAIN_ERROR';

export const CREATE_SUBDOMAIN = 'CREATE_SUBDOMAIN';
export const CREATE_SUBDOMAIN_ERROR = 'CREATE_SUBDOMAIN_ERROR';

export const UPDATE_SUBDOMAIN = 'UPDATE_SUBDOMAIN';
export const UPDATE_SUBDOMAIN_ERROR = 'UPDATE_SUBDOMAIN_ERROR';

export const DELETE_SUBDOMAIN = 'DELETE_SUBDOMAIN';
export const DELETE_SUBDOMAIN_ERROR = 'DELETE_SUBDOMAIN_ERROR';